#!/usr/bin/env bash
set -euo pipefail

NCS_VERSION="${NCS_VERSION:-v2.7.0}"
ZEPHYR_SDK_VERSION="${ZEPHYR_SDK_VERSION:-0.16.5}"
NCS_DIR="${NCS_DIR:-$HOME/ncs}"
ZEPHYR_SDK_DIR="${ZEPHYR_SDK_DIR:-$HOME/zephyr-sdk}"
WORKSPACE_DIR="${NCS_DIR}/${NCS_VERSION}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USER_BASE="$(python3 -m site --user-base)"
export PATH="${USER_BASE}/bin:${PATH}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--deps-only] [--skip-deps] [--skip-sdk] [--skip-ncs]

Installs/updates local nRF Connect SDK + Zephyr SDK build environment.

Defaults:
  NCS_VERSION=${NCS_VERSION}
  ZEPHYR_SDK_VERSION=${ZEPHYR_SDK_VERSION}
  NCS_DIR=${NCS_DIR}
  ZEPHYR_SDK_DIR=${ZEPHYR_SDK_DIR}

Environment overrides:
  NCS_VERSION, ZEPHYR_SDK_VERSION, NCS_DIR, ZEPHYR_SDK_DIR
EOF
}

DEPS_ONLY=0
SKIP_DEPS=0
SKIP_SDK=0
SKIP_NCS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deps-only) DEPS_ONLY=1 ;;
    --skip-deps) SKIP_DEPS=1 ;;
    --skip-sdk) SKIP_SDK=1 ;;
    --skip-ncs) SKIP_NCS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1"; usage; exit 1 ;;
  esac
  shift
done

log() { printf "\n[%s] %s\n" "$(date +"%H:%M:%S")" "$*"; }

install_host_deps() {
  if [[ "$SKIP_DEPS" -eq 1 ]]; then
    return
  fi

  log "Installing host dependencies"
  if command -v brew >/dev/null 2>&1; then
    brew update
    brew install cmake ninja gperf ccache dfu-util dtc wget python || true
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends \
      git cmake ninja-build gperf ccache dfu-util device-tree-compiler \
      xz-utils file wget python3 python3-pip
  else
    log "No supported package manager found. Install cmake, ninja, gperf, dtc, dfu-util manually."
  fi

  python3 -m pip install --user --break-system-packages --upgrade pip
  python3 -m pip install --user --break-system-packages --upgrade west ninja
}

setup_ncs() {
  if [[ "$SKIP_NCS" -eq 1 ]]; then
    return
  fi

  mkdir -p "${NCS_DIR}"

  if [[ ! -d "${WORKSPACE_DIR}/.west" ]]; then
    log "Initializing nRF Connect SDK workspace at ${WORKSPACE_DIR}"
    west init -m https://github.com/nrfconnect/sdk-nrf --mr "${NCS_VERSION}" "${WORKSPACE_DIR}"
  else
    log "nRF Connect SDK workspace already exists: ${WORKSPACE_DIR}"
  fi

  log "Updating NCS repositories"
  (
    cd "${WORKSPACE_DIR}"
    west update -o=--depth=1 -n
    west blobs fetch hal_nordic
    west zephyr-export
    python3 -m pip install --user --break-system-packages -r zephyr/scripts/requirements.txt
  )
}

setup_zephyr_sdk() {
  if [[ "$SKIP_SDK" -eq 1 ]]; then
    return
  fi

  mkdir -p "${ZEPHYR_SDK_DIR}"
  SDK_BASE="${ZEPHYR_SDK_DIR}/zephyr-sdk-${ZEPHYR_SDK_VERSION}"

  if [[ -d "${SDK_BASE}" ]]; then
    log "Zephyr SDK already exists: ${SDK_BASE}"
    return
  fi

  OS_NAME="$(uname -s)"
  ARCH_NAME="$(uname -m)"

  case "${OS_NAME}:${ARCH_NAME}" in
    Linux:x86_64) SDK_ARCHIVE="zephyr-sdk-${ZEPHYR_SDK_VERSION}_linux-x86_64.tar.xz" ;;
    Darwin:arm64) SDK_ARCHIVE="zephyr-sdk-${ZEPHYR_SDK_VERSION}_macos-aarch64.tar.xz" ;;
    Darwin:x86_64) SDK_ARCHIVE="zephyr-sdk-${ZEPHYR_SDK_VERSION}_macos-x86_64.tar.xz" ;;
    *) echo "Unsupported host for automatic Zephyr SDK install: ${OS_NAME} ${ARCH_NAME}"; exit 1 ;;
  esac

  SDK_URL="https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZEPHYR_SDK_VERSION}/${SDK_ARCHIVE}"
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "${TMP_DIR}"' EXIT

  log "Downloading Zephyr SDK ${ZEPHYR_SDK_VERSION}"
  curl -L "${SDK_URL}" -o "${TMP_DIR}/${SDK_ARCHIVE}"

  log "Extracting Zephyr SDK"
  tar -C "${ZEPHYR_SDK_DIR}" -xf "${TMP_DIR}/${SDK_ARCHIVE}"

  log "Running Zephyr SDK setup"
  "${SDK_BASE}/setup.sh" -h -c
}

write_env_file() {
  ENV_FILE="${REPO_ROOT}/scripts/ncs-env.sh"
  log "Writing environment helper: ${ENV_FILE}"
  USER_BASE="$(python3 -m site --user-base)"
  cat > "${ENV_FILE}" <<EOF
#!/usr/bin/env bash
# Generated by scripts/setup_ncs_zephyr.sh
export WEST_TOPDIR="${WORKSPACE_DIR}"
export ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
export ZEPHYR_SDK_INSTALL_DIR="${ZEPHYR_SDK_DIR}/zephyr-sdk-${ZEPHYR_SDK_VERSION}"
export PATH="${USER_BASE}/bin:\$HOME/.local/bin:\$PATH"
EOF
  chmod +x "${ENV_FILE}"
}

install_host_deps

if [[ "$DEPS_ONLY" -eq 1 ]]; then
  write_env_file
  log "Done (deps only)."
  exit 0
fi

setup_ncs
setup_zephyr_sdk
write_env_file

log "Environment setup complete."
log "Next: source scripts/ncs-env.sh && ./scripts/build_xiao_minimal.sh"
